### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Angryboy29** [Angryboy29/koa_test#1]
### Todo

- [x] 组件模板添加默认style、className、children接受
- [x] 根据类型声明和注释（jsdoc、tsdoc）生成文档
- [x] 识别TS类型、自动生成mock数据及Demo  
- [x] 自动在components文件中引入导出、按照上浮模式规范分块儿
- [ ] Props使用方式
- [ ] 类型及组件声明及导出最佳实践
- [ ] 组件上报、微组件、自动化测试
- [ ] demo沙盒
- [ ] 组件间依赖、store依赖分析、全局样式依赖
- [ ] 模式应用到hooks及其他形式
